(() => {
const scenes=[...document.querySelectorAll('.scene-ui')],dots=[...document.querySelectorAll('.scene-nav button')],topScene=document.getElementById('topScene'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
let index=0,busy=false,touchY=null,reviewIndex=0;
const go=(n,force=false)=>{n=(n+scenes.length)%scenes.length;if((n===index&&!force)||busy)return;busy=true;const prev=scenes[index],next=scenes[n];prev.classList.remove('is-active');prev.classList.add('is-exit');next.classList.add('is-active');index=n;dots.forEach((d,i)=>d.classList.toggle('is-active',i===index));topScene.textContent=String(index+1).padStart(2,'0');window.DPWorld?.setScene(index);setTimeout(()=>{prev.classList.remove('is-exit');busy=false},reduce?30:900)};
const next=d=>go(index+d);
document.querySelectorAll('[data-goto]').forEach(e=>e.addEventListener('click',x=>{x.preventDefault();go(+e.dataset.goto,true)}));
addEventListener('wheel',e=>{if(document.querySelector('.brief-modal.is-open,.ai-modal.is-open'))return;if(Math.abs(e.deltaY)>18)next(e.deltaY>0?1:-1)},{passive:true});
addEventListener('keydown',e=>{if(document.querySelector('.brief-modal.is-open,.ai-modal.is-open')){if(e.key==='Escape')document.querySelectorAll('.brief-modal,.ai-modal').forEach(m=>m.classList.remove('is-open'));return}if(['ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();next(1)}if(['ArrowUp','PageUp'].includes(e.key)){e.preventDefault();next(-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(4)}});
addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchY=e.clientY},{passive:true});addEventListener('pointerup',e=>{if(touchY==null)return;const d=e.clientY-touchY;if(Math.abs(d)>45)next(d<0?1:-1);touchY=null},{passive:true});
document.querySelectorAll('[data-link]').forEach(e=>e.addEventListener('click',()=>location.href=e.dataset.link));
if(matchMedia('(pointer:fine)').matches&&!reduce){document.querySelectorAll('[data-tilt],.service-card,.dash-panel,.orbit-card,.glass-card').forEach(el=>{el.addEventListener('pointermove',e=>{const s=el.closest('.scene-ui');if(s&&!s.classList.contains('is-active'))return;const r=el.getBoundingClientRect(),x=e.clientX/r.width-(r.left/r.width)-.5,y=e.clientY/r.height-(r.top/r.height)-.5;const m=el.hasAttribute('data-tilt')?5:7;el.style.transform=`perspective(1000px) rotateX(${(-y*m).toFixed(2)}deg) rotateY(${(x*m).toFixed(2)}deg) translateZ(7px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/r.width*12,y=(e.clientY-r.top-r.height/2)/r.height*12;el.style.transform=`translate3d(${x}px,${y}px,0)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
const reviews=[...document.querySelectorAll('.review-card')],count=document.getElementById('reviewCount');const showReview=n=>{reviewIndex=(n+reviews.length)%reviews.length;reviews.forEach((r,i)=>r.classList.toggle('is-active',i===reviewIndex));count.textContent=`${String(reviewIndex+1).padStart(2,'0')} / 03`};document.querySelector('[data-review="prev"]').onclick=()=>showReview(reviewIndex-1);document.querySelector('[data-review="next"]').onclick=()=>showReview(reviewIndex+1);
const answers={services:'Performance / paid social, social presence, digital experiences, brand strategy, creator partnerships and growth consulting — connected as one operating system.',start:'Choose a service card, open the dedicated layer, then use the project brief. We scope the pressure point first and build in focused sprints.',time:'First replies are typically within one working day. Delivery time depends on the layer and scope; builds are structured into clear stages.',team:'Yes. Digital Pillars can plug into an existing marketing, design or development team as a specialist layer, lead, or delivery partner.'};
document.querySelectorAll('[data-answer]').forEach(q=>q.addEventListener('click',()=>{const box=q.closest('.ai-window,.ai-panel')?.querySelector('.answer-box');if(box)box.textContent=answers[q.dataset.answer]||'Select another question.'}));
const brief=document.getElementById('briefModal'),ai=document.getElementById('aiModal');document.querySelectorAll('[data-brief]').forEach(b=>b.onclick=()=>brief.classList.add('is-open'));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>brief.classList.remove('is-open'));document.querySelector('[data-open-ai]').onclick=()=>ai.classList.add('is-open');document.querySelectorAll('[data-close-ai]').forEach(b=>b.onclick=()=>ai.classList.remove('is-open'));
document.getElementById('briefForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),sub=encodeURIComponent(`Digital Pillars enquiry — ${f.get('company')||f.get('name')}`),body=encodeURIComponent(`Name: ${f.get('name')}\nEmail: ${f.get('email')}\nCompany: ${f.get('company')}\n\nProject:\n${f.get('message')}`);location.href=`mailto:hello@digitalpillars.studio?subject=${sub}&body=${body}`};
const pct=document.getElementById('loadPct'),loader=document.getElementById('loader');let p=0;const tick=setInterval(()=>{p=Math.min(100,p+Math.round(6+Math.random()*13));pct.textContent=String(p).padStart(2,'0');if(p>=100){clearInterval(tick);setTimeout(()=>loader.classList.add('loader-done'),reduce?30:280)}},55);
})();