const scenes=[...document.querySelectorAll('.scene')], nav=[...document.querySelectorAll('.nav__item')], nameEl=document.getElementById('sceneName'), numEl=document.getElementById('sceneNum');
const names=['CORE / DIGITAL PILLARS','BUILD / PERFORMANCE ENGINE','SYSTEM / SIX LAYERS','PROOF / CLIENT VOICE','AI / NEXT STEP'];let index=0,busy=false,touchY=null;
function goTo(n){n=(n+scenes.length)%scenes.length;if(n===index||busy)return;busy=true;const prev=scenes[index];prev.classList.remove('is-active');prev.classList.add('is-leaving');setTimeout(()=>prev.classList.remove('is-leaving'),850);index=n;scenes[index].classList.add('is-active');nav.forEach((b,i)=>b.classList.toggle('is-active',i===index));numEl.textContent=String(index+1).padStart(2,'0');nameEl.textContent=names[index];window.DPWorld?.setScene(index);setTimeout(()=>busy=false,720)}
function pointerDown(e){if(e.pointerType==='touch')touchY=e.clientY}function pointerUp(e){if(touchY==null)return;const dy=e.clientY-touchY;if(Math.abs(dy)>45)goTo(index+(dy<0?1:-1));touchY=null}
addEventListener('wheel',e=>{if(document.querySelector('.modal.is-open,.brief.is-open'))return;if(Math.abs(e.deltaY)<8)return;goTo(index+(e.deltaY>0?1:-1));},{passive:true});addEventListener('pointerdown',pointerDown,{passive:true});addEventListener('pointerup',pointerUp,{passive:true});addEventListener('keydown',e=>{if(e.key==='ArrowDown'||e.key==='PageDown'||e.key===' '){e.preventDefault();goTo(index+1)}else if(e.key==='ArrowUp'||e.key==='PageUp'){e.preventDefault();goTo(index-1)}else if(e.key==='Home'){e.preventDefault();goTo(0)}else if(e.key==='End'){e.preventDefault();goTo(scenes.length-1)}});
nav.forEach(b=>b.addEventListener('click',()=>goTo(+b.dataset.scene)));
document.querySelectorAll('[data-scene]').forEach(b=>{if(b.classList.contains('nav__item'))return;b.addEventListener('click',e=>{const n=b.dataset.scene;if(n!=null)goTo(+n)})});
document.querySelectorAll('[data-href]').forEach(el=>el.addEventListener('click',()=>{location.href=el.dataset.href}));
// magnetic + tilt
const fine=matchMedia('(pointer:fine)');if(fine.matches){document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)/r.width*12,y=(e.clientY-r.top-r.height/2)/r.height*12;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});document.querySelectorAll('.float-card,.dash-card,.orbit-card,.assistant-preview').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();const rx=((e.clientY-r.top)/r.height-.5)*-8,ry=((e.clientX-r.left)/r.width-.5)*10;el.style.transform=`perspective(800px) rotateX(${rx}deg) rotateY(${ry}deg) translateZ(5px)`});el.addEventListener('mouseleave',()=>el.style.transform='')})}
// reviews
let review=0;const reviews=[...document.querySelectorAll('.review')];function showReview(n){review=(n+reviews.length)%reviews.length;reviews.forEach((r,i)=>r.classList.toggle('is-active',i===review))}document.getElementById('prevReview').onclick=()=>showReview(review-1);document.getElementById('nextReview').onclick=()=>showReview(review+1);
const answers={services:'Six connected layers: performance / paid social, social presence, web experiences, brand strategy, creator partnerships and growth consulting.',start:'Start with a brief. We map the pressure point, define the first system to build, then move into a focused sprint.',turnaround:'Most first replies land within one working day. Timelines vary by scope, with focused builds typically structured in staged sprints.',team:'Yes. Digital Pillars can plug into an existing marketing, design or development team and operate as the specialist layer.'};
function wireFaq(root=document){root.querySelectorAll('.faq-q').forEach(q=>q.onclick=()=>{const a=q.closest('.modal__panel,.assistant-preview')?.querySelector('.assistant-answer');if(a)a.textContent=answers[q.dataset.answer]||'Let’s map the next step together.'})}wireFaq();
const modal=document.getElementById('assistantModal');document.getElementById('assistantDockBtn').onclick=()=>modal.classList.add('is-open');document.getElementById('openAssistant').onclick=()=>modal.classList.add('is-open');document.querySelectorAll('[data-close-assistant]').forEach(x=>x.onclick=()=>modal.classList.remove('is-open'));
const brief=document.getElementById('contact');function openBrief(){brief.classList.add('is-open');brief.setAttribute('aria-hidden','false')}document.getElementById('contactBtn').onclick=openBrief;document.querySelector('.start').onclick=e=>{e.preventDefault();openBrief()};document.getElementById('closeBrief').onclick=()=>brief.classList.remove('is-open');document.getElementById('briefForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const sub=encodeURIComponent(`Digital Pillars enquiry — ${f.get('company')||f.get('name')}`);const body=encodeURIComponent(`Name: ${f.get('name')}\nEmail: ${f.get('email')}\nCompany: ${f.get('company')}\n\nProject:\n${f.get('message')}`);location.href=`mailto:hello@digitalpillars.studio?subject=${sub}&body=${body}`});
// boot
let pct=0;const bootPct=document.getElementById('bootPct');const boot=document.getElementById('boot');const timer=setInterval(()=>{pct=Math.min(100,pct+Math.ceil(Math.random()*13));bootPct.textContent=pct+'%';if(pct>=100){clearInterval(timer);setTimeout(()=>boot.classList.add('is-done'),250)}},90);window.__dpScene=0;
